name: Echo on demand
on: workflow_dispatch
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: first message
        run: echo "Hello World!"
      - name: last message
        run: echo "Done!"
